---

- name: Fail if required Keycloak settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - keycloak_identifier
    - keycloak_uid
    - keycloak_gid
    - keycloak_hostname
    - keycloak_path_prefix
    - keycloak_container_network
    - keycloak_database_hostname
    - keycloak_database_name
    - keycloak_database_username
    - keycloak_database_password

- when: keycloak_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Keycloak Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - keycloak_container_labels_traefik_hostname
        - keycloak_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `keycloak_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if keycloak_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          keycloak_container_labels_traefik_path_prefix (`{{ keycloak_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/keycloak`).
      when: "keycloak_container_labels_traefik_path_prefix != '/' and keycloak_container_labels_traefik_path_prefix[-1] == '/'"
